### ISSUE TITLE
Release of 2.0.8b

### ISSUE THREAD

**Issue by LePresidente** [TanninOne/modorganizer#1026]
Should the release of 2.0.8b be the new version using the latest build enviroment no real changes regarding skyrimse?

If so i I have the installer working, so should i release to nexusmods as is? 

We can make 2.0.9b being all the latest changes for skyrimse once we get going on coding the c++ code.

Progress might bring more people here and help?

**Comment by Deucezor** [comment]
No idea about what you talking about since im a big noob in code, but if you could send me the installer in pm or something I would appreciate, thanks :p

**Comment by BlayeeR** [comment]
I think next release should contain SkyrimSE support. It's what people are waiting for. Take your time and do what you think is correct.

**Comment by LePresidente** [comment]
Think those three currently the main ones, so once they fixed we can release

**Comment by TanninOne** [comment]
If you do a new release, please do me a favor and change the message that asks people to send crash dumps to me (in main.cpp of the "modorganizer" repo).
The crash dumps are occasionally very useful to find bugs so you might have them send to you. The dump contains mostly a stack trace and local variables of only the last stack frame but that may still contain passwords or other confidential info so better not instruct users to upload the dumps publicly.

Remember to keep the pdbs around per release if you want to be able to use crash dumps.

Also, the auto updater is currently hard-coded to use my repo for releases (in selfupdater.cpp of "modorganizer"). Going forward you may want to aim that at your own fork so that updates work in the future.

**Comment by LePresidente** [comment]
Thanks will make sure that it is changed. I was able to grab modorganizer@gmail.com so will use that in the future for communication.

**Comment by LePresidente** [comment]
The usvfs not compiling the 32bit binary is a serious pain

**Comment by ZachHaber** [comment]
What all needs to be done on the c++/Qt side for 2.0.9? I am familiar with them, so I figure I can probably help if you point me in the correct direction.

**Comment by LePresidente** [comment]
All the bugs referenced here pretty much, The usvfs is probably the biggest issue

With umbrella set the architechture to x86 and run the command unimake.py -d "c:/Build" usvfs 

you might need to add .depend("boost") to usvfs project but the shared build will fail, then remove the .depend("boost") and build again

**Comment by AronaxAE** [comment]
@LePresidente Any updates?

**Comment by LePresidente** [comment]
Sorry no, had no time. Reverted back to msvc2013 though my vm is being slow

**Comment by LePresidente** [comment]
Ok if someone can fix either of those usvfs errors then we can release

**Comment by LePresidente** [comment]
Ok try it see how it goes
https://github.com/LePresidente/modorganizer/releases/tag/v2.0.8b

**Comment by LePresidente** [comment]
Lootcli and skyrimse thumbnails not fixed

**Comment by BlayeeR** [comment]
Everything except that looks good on first sight, I will try to mod sse using this version so maybe we will find more bugs. 

And there's a small typo in installer. Plugin for SkyrimSE has the same name as Skyrim
![f0c19be91eae998eb07658db66a53da3](https://cloud.githubusercontent.com/assets/24255215/21106253/bb86ae10-c08d-11e6-8f6f-0b615c12f0e0.png)

**Comment by LePresidente** [comment]
Cool thanks, fixed the typo.

**Comment by ZachHaber** [comment]
By skyrimSE thumbnails, are you referring to the save game images? If so, I have an idea for fixing that, I just need to finish getting the project to compile properly before I start working on the code. Currently stuck on compiling plugin_python. Showing LNK1169 error.

**Comment by LePresidente** [comment]
@ZachHaber, what compiler you using currently msvc2013 builds completely? also are you using tannin or my repo. 

The link error was fixed for both recently. maybe pull from my repos again

**Comment by ZachHaber** [comment]
I believe it's using MSVC2015. I think at this point it is more of a mix. I pulled from your repo for the plugin_python just now, and it is still failing, but with different errors.
[stdout.txt](https://github.com/TanninOne/modorganizer/files/646648/stdout.txt)
[stderr.txt](https://github.com/TanninOne/modorganizer/files/646649/stderr.txt)

**Comment by LePresidente** [comment]
OK that error is due to that you not using my repo for gamebyro and modorganizer I added gamenexusname to allow the skyrimse plugin to look at the correct place on nexusmods

**Comment by LePresidente** [comment]
Must still push it sorry

**Comment by BlayeeR** [comment]
Should I create new issue thread for new issues with 2.0.8 or write them there?

**Comment by LePresidente** [comment]
New thread

**Comment by LePresidente** [comment]
This has been released, will create new thread for 2.0.9

**Comment by mlandstreet** [comment]
Is there somewhere that actually gives the link for 2.08b? I have been going in circles for 30 minutes.

Thanks!

**Comment by LePresidente** [comment]
https://github.com/LePresidente/modorganizer/releases/tag/v2.0.8b
