### ISSUE TITLE
Mod Organizer 2 - Vanilla Fallout 4 CTD before Main Menu

### ISSUE THREAD

**Issue by Goofysoccer** [TanninOne/modorganizer#381]
I know other people have had this issue, but I have a clean install of Fallout 4, no mods at all, no extra  DLLs, etc. The game, when launched through Mod Organizer, gives me a black screen at "Press any button to continue" and then CTD after 2-3 seconds. I have tried putting my MO folder in the FO4 one and that didn't work. My work directory is also set correctly. I am running on Windows 7 x64 and I have no idea what the issue is.

UPDATE: For some reason now it just CTD before the "Press any button to continue" even pops up. I simply open the game, and this happens both with the launcher and without, it has a black screen, and then the game crashes after a second or two.

LOG: 
[usvfs-2015-11-26_19-39-01.log.txt](https://github.com/TanninOne/modorganizer/files/45224/usvfs-2015-11-26_19-39-01.log.txt)

**Comment by Goofysoccer** [comment]
Bump?

**Comment by strangerism** [comment]
Ok I don't think this is a forum where we can bump threads to get attention etc. I guess the point here is to provide feedback of the alpha so the devs can figure out what needs to be done to release the software. As your case is somehow similar to other issues raised it would have been better to tail it there rather than make a new one. Anyway as I am lurking often here I can't resists to have a look and see if I can help somehow. I am a user like though so no promises.

Looking at the logs I can see a "fishy" line that is repeated lots of times

13:39:04.830 <%P:8372> [D] NtOpenFile [source=\??\C:\Users\Natan\Documents\My Games\Fallout4\Fallout4.INI] [rerouted=\??\C:/Program Files (x86)/Mod Organizer - Fallout 4/profiles/Default/fallout4.ini] [*FileHandle=<null>] [res=err c0000034]

the part [*FileHandle=<null>] [res=err c0000034] could tell use that the MO cannot create an handle for Fallout4.ini from your games folder to the MO folder with is C:/Program Files (x86)/Mod Organizer - Fallout 4/profiles/Default/fallout4.ini 

the reason could be either because MO is installed in program files or doesn't have Administrative right to do so. Bear in mind this are assumptions, I haven't wrote the code nor and familiar with the logs.

You could try the following:

1) reinstall MO to a directory which is not under OS jurisdiction, like the root of C: or another drive.
2) run MO as administrator
3) both 1 and 2
4) install Fallout4 somewhere else like in (1)
5) both 1,2 and 4

Also in the logs there is trace of NVidia shadow play related files with refers the same error type, maybe this could cause issues with MO if run at the same time. So overall it seems MO fails to handle the ini file and is hooking stuff that interfere (NVidia Shadowplay).

try to close any thing like that, Kill GeforceExperience if that is the case, or any overlay like rivatuner or Afterburner etc.

I repeat this is all a guessing from my part. Hoe it helps so you can go on with the testing and feedback.

**Comment by NexusAU** [comment]
I was having this same issue and moving Mod Organizer from my Fallout 4 directory to just C:/ fixed the issue. So I guess the problem has to do with MO not having the the proper rights to operate in program files, even when running a Administrator.

**Comment by TanninOne** [comment]
C0000034 is basically "file not found" so this is (probably) more about the file being missing or path incorrect than about permissions.

**Comment by TanninOne** [comment]
Oh, i have an idea. The new vfs lib works on a lower level api than the old one, maybe windows itself is using some virtualisation internally for the "program files x86" folder so it may have a different name in the low level api (windows does this for several directories, i.e. C:/windows/syswow64 is also just a link.)

Could you plese try. Installing mo2 to "c:/program files" without the x86?
Mo2 is a 64bit application so that is the correct path anyway

**Comment by NexusAU** [comment]
I tried installing MO2 to "C:/Program Files" without the x86 and it's giving me the same crash on startup. Moving it back to just C:/ works fine.

That was running as Admin too.

**Comment by WereWookiee** [comment]
I'm running MO as administrator and having the same CTD issue, though my fallout 4/Mod Organizer is installed in a custom directory: C:\Games\Steam Games\steamapps\common\Fallout 4\Mod Organizer

**Comment by Goofysoccer** [comment]
@TanninOne I tried moving Mod Organizer to C:/ and that didn't work. I then tried moving mod organizer to C:/Program Files without the x86 as well, and that didn't work either. I ran both as admin. It's really weird why this issue is happening because I am running it completely vanilla. 

Also, instead of having an instant CTD, it reverted back to the CTD after "Press any button to continue."

LOGS: 
MO running in C:/ - http://pastebin.com/G6WmmnfA
MO running in C:/Program Files without the x86 - http://pastebin.com/eZ6dB5KW

**Comment by TanninOne** [comment]
Should be fixed in alpha 2

**Comment by MithosFall** [comment]
Just downloaded alpha 2 and the same problems still seem to be happening.  In fact, it doesn't even feel like I updated at all, even though some of the files that overwrote the alpha 1 install were larger or smaller.  All of the executables I try to launch with alpha 2 still fail.  I even tried a completely fresh install of alpha 2 on a separate drive and the problems persisted.  Also, the little section at the bottom of the MO2 window says it's still version 2.0.0.0.

**Comment by Twinki14** [comment]
Just completely wiped the MO2 Directory and updated, still getting a CTD.

**Comment by DeathProxie** [comment]
Having the same issue, and tried moving the MO Folder around with no luck. I haven't tried moving my Fallout 4 folder yet. Here are logs of my most recent attempt. This is with Alpha 2. Oddly enough it has started with MO a time or two but it was like a fluke and wouldn't do it again after closing and trying.

http://pastebin.com/uc6ay0xt - usvfs-2015-11-29_18-02-55.log
http://pastebin.com/QqAwB3zE - mo_interface.log

**Comment by grasmann** [comment]
Did you guys try to move the whole game to another hdd?
Maybe the problem is that the game is in C:/Program Files.
I've got my steamlibrary on another hdd, moved fallout 4 to my ssd and symlinked it to the library.
Alpha 2 seems to work pretty good for me.
I think the log looks good as well.
The last line is showing an access violation error or something in that direction but it's starting correctly and the mods are working.
[usvfs-2015-11-30_08-25-37.txt](https://github.com/TanninOne/modorganizer/files/47094/usvfs-2015-11-30_08-25-37.txt)

**Comment by DeathProxie** [comment]
Yes I tried moving my game to D:\Steam\Fallout 4 and I still have the same issues. Not using the reshade DLL game crashes with the .dmp provided. With it the game makes it further to black screen, hear the music for a second with press any key then it crashes a second later(no idea why it gets a little further with that dll in the folder). With the DLL there's some kind of issue with the users folder it appears, it doesn't properly load them. This is supported by the fact that my game opens in window at a low resolution instead of fullscreen with my 1920x1080 resolution. It works fine without MO.

No Mods atm.

**Comment by MithosFall** [comment]
My games are never in Program Files.  I have specific games folders for them.

**Comment by Lagosaurus** [comment]
Having this issue with Alpha 2 on Windows 7 x64. The game window will open for a couple of seconds before closing without an error message. My .ini settings aren't being read properly either, which is evidenced by the game launching at its default resolution in windowed mode. The only thing that really stuck out to me in the logs were hundreds of instances of 

`[D] NtOpenFile [source=\??\C:\Users\Documents\My Games\Fallout4\Fallout4.INI] [rerouted=\??\D:/Fallout 4/ModOrganizer2/ModOrganizer2/profiles/Default/fallout4.ini] [*FileHandle=<null>] [res=err c0000034]`

**Comment by grasmann** [comment]
"C:\Users\Documents" can't be correct.
That directory doesn't exist.
It should be "C:\Users\[YourUsername]\Documents"

What is your username?
Are you using the "administrator" account?
Or did you move your documents folder in windows?
Is there something special with your windows configuration?

**Comment by Lagosaurus** [comment]
I redacted the username, the path is correct.

**Comment by TanninOne** [comment]
Ok, it appears mo is currently not compatible with win 7. now I wish i still had a win 7 installation... :/

**Comment by WereWookiee** [comment]
I briefly considered upgrading to 10 for this, lol.  But no, I'm gonna wait on that.  
I have a similar issue when using your newer version of MO, except now Fallout 4 crashes on startup through MO, rather than sort of getting to the main title screen and then crashing.

**Comment by MithosFall** [comment]
@TanninOne: Well that makes alot of sense now.  lol

**Comment by Twinki14** [comment]
@TanninOne Are you planning on Windows 7 Compatibility? I really hope so >.<

**Comment by NoShotz** [comment]
@Twinki14 Obviously he will, as a large portion of the MO users, are probably using windows 7

**Comment by WhiteZeroX** [comment]
@TanninOne Spin up a Win7 Virtual Machine for testing? If you don't have a spare Win7 license and want to know how to permanently "demo" Windows, let me know and I can help you there.

**Comment by Lagosaurus** [comment]
Tested Alpha 2 on Windows 7/8/10, looks like the issue is exclusive to Windows 7.

**Comment by unobtainer** [comment]
I'm also on Win7 x64 (with no plans to upgrade on this machine) and am getting a CTD while loading Fallout4.exe from MO (access violation).

Both MO and FO4 are outside the Windows file structure (on the P: drive), and running both as admin doesn't help.  I've tried with and without ENBoost, and with and without FTOP. Not yet running FOSE4 or F4SE or whatever we're calling it this time around. Disabling the Steam overlay doesn't help. 

 A manually modded install with the same mods is running fine, so it seems to be a VFS issue.

I also pulled some Windows updates that I thought might help (inluding a C runtime backported for Win10 app compatibility on Win7) to no avail.

Sadly I don't have a Win8 or Win10 machine with enough horsepower to run FO4 to cross-test with, but happy to do anything else I can to help get MO2 running on Win7. It's only been a few weeks with FO4 and I miss MO terribly.

**Comment by Twinki14** [comment]
@TanninOne Any update on this issue? Been constantly checking for a new release with a fix for this issue.

**Comment by MithosFall** [comment]
Yeah, any sort of Win 7 release, even with the bugs, would be super nice.

**Comment by jaKz9** [comment]
Any update on a release with Windows 7 support? :(

**Comment by blomstertj** [comment]
I'm having this problem too on Windows 10 64-bit.  The game crashes before main menu when using Mod Organizer 2.0.6.  Running the exact same mod list and exact same load order as I did previously.  I had Fallout 4 and Mod Organizer on my non-Windows partition on a seperate hard drive.  It worked flawlessly.  I uninstalled Fallout 4 and Mod Organizer and install them to C:\Games\Fallout 4 and C:\Games\Fallout 4 MO.  I wanted faster load times with my SSD.  The game does start up and doesn't crash when not using MO to launch.  I tried running MO as admin but that did not help.

Here's another log but with log level set to Error only: https://drive.google.com/open?id=1wbZtWf64Kz36ZS8FdtwlHRhTT5SqyYBV9UzwKLZbpfw

The last line seems interesting to me.  Any ideas?

**Comment by Eliams0** [comment]
Fallout 4 crashing on the start of the game is very common thing these days. I would highly recommended to troubleshoot the problem once and for all. Just follow the steps given in here. Hope it helps you solve your problem. [https://appuals.com/fix-fallout-4-crash-startup/](https://appuals.com/fix-fallout-4-crash-startup/)

**Comment by blomstertj** [comment]
I wouldn't have posted a bug report if I didn't try those methods first.

**Comment by WhiteZeroX** [comment]
@Eliams0 @blomstertj You guys know this project is dead, right? Tannin has moved on to working on NMM/Vortex

**Comment by LePresidente** [comment]
Um not completely just migrated to my repo and there are a few working on it

**Comment by WhiteZeroX** [comment]
@LePresidente ah ok, I didn't see any commits on the main branch, so I assumed it was dead too. But I see other parts getting updated. Cheers!
