### ISSUE TITLE
Fallout 4 Crashes instantly when launching through MO2

### ISSUE THREAD

**Issue by NexusAU** [TanninOne/modorganizer#388]
I'm having an issue where FO4 will show a black screen and crash instantly when launching it through MO. Here's the issue happening: https://gfycat.com/LiveOddChamois

My Fallout 4 is completely Vanilla and this happens even with no mods installed in MO.
I'm using Win10 64-Bit btw.

**Comment by strangerism** [comment]
are you using reshade btw? Also could you post the logs when launching with no mods installed?

**Comment by NexusAU** [comment]
I'm not using reshade, the game is completely vanilla.

Here's the logs:
[usvfs-2015-11-27_10-25-23.txt](https://github.com/TanninOne/modorganizer/files/45615/usvfs-2015-11-27_10-25-23.txt)
[mo_interface.txt](https://github.com/TanninOne/modorganizer/files/45622/mo_interface.txt)

**Comment by strangerism** [comment]
Cannot see any errors in the log files, however, it might not be the reason of your crash although one recommendation for modding Bethesda games has been to my knowledge to install anywhere but "Program Files". Once again I am not sure it could be one of those false myth out there.

If you want to go ahead and make this change you can do this easily and fast (there are some guides if you google it). You need to backup through steam your fallout game first (Steam-->Restore or Backup games) and save the backup somewhere, then delete the game local cache, and lastly restore the game using the same function and this time you choose a different location by creating a new steam library somewhere else in your drive (i.e. c:\steamlibrary\) where to store the game. You can have multiple steam libraries so this won't mess with your other games.

**Comment by ThosRTanner** [comment]
It is true generally if you want to mod, you need write access to the games data directory. However, Mod Organiser works in such a way that this is no longer true and you can install Bethseda games in the default (protected) location

**Comment by NexusAU** [comment]
Problem solved by moving my Mod Organizer directory straight to C:/ and out of Program Files.

**Comment by Muscl3geek** [comment]
I'm having this issue as well. Just removed all mods and still happening.
