### ISSUE TITLE
[MO2A4] All applications run through it crash as soon as they are run (Fallout 4)

### ISSUE THREAD

**Issue by xRedDragon** [TanninOne/modorganizer#567]
I have recently reinstalled Win7 (64-bit) and I also tried running MO2's latest alpha (4). However any application I try to run (Fallout 4, the Launcher, FO4Edit and F4SE) all crash as soon as they are run (application has stopped working). 
I also tried Alpha 3 with the same result. I was however able to run it before a clean install of windows.

This is what I get from the log file:
18:05:41.626 <4728:4308> [D] GetFileAttributesExW [lpFileName=\\?\C:\Users\] [reroute.fileName()=C:\Users] [res=1] [::GetLastError()=0]
18:05:41.627 [W] windows exception c0000005 from C:\Windows\system32\MSVCR120.dll

Has anyone had any similar issues with this? I tried googleing the issue but didn't come up with anything relevant.

P.S. MO 1.3.11 seems to work fine with Skyrim, Oblivion, FO3 and FNV.

**Comment by DeadMor0z** [comment]
The same problem here. Alpha2 is running Fallout4 ok, FO4Edit don't work (the same error).
The strange thing is when I first installed Alpha4 - it run everything without any problem. Next time I started Alpha4, this issue appeared. Removing and installing back didn't help. Rolled back to Alpha2 for now.

**Comment by Dragon02022003** [comment]
Try downloading and installing Visual C++ Redistributable Packages for Visual Studio 2013 from the microsoft website (would link but I don't know if it's allowed). 

"18:05:41.627 [W] windows exception c0000005 from C:\Windows\system32\MSVCR120.dll" Exception c0000005 by what I've read on numerous other games sites is an access invalidation error or something like that, but reinstalling or updating to Visual C++ Redistributable Packages for Visual Studio 2013 seems to fix most if not all errors with this dll.

**Comment by xRedDragon** [comment]
Reinstalled Visual C++ and it didn't fix the crashes.

**Comment by DeadMor0z** [comment]
Didn't  help me either. Crash dtill persist.

**Comment by DeadMor0z** [comment]
Now I have this error with FO4Edit:
Fatal: Error loading plugin list: <EAccessViolation: Access violation at address 5FE3F8E2 in module 'MSVCR120.dll'. Read of address 01559000>

**Comment by michaelrw10** [comment]
I used to get crashes like this until I uninstalled every single manager and FO4. If you have NMM installed, it has been implicated as a cause.

**Comment by ualexen92** [comment]
Same error while the windows is unfocused, however if you just press **Run** and don't do anything util your game is fully load it should work...

**Comment by GoslingMyles** [comment]
Currently having the same problem. FO4Edit was working fine with MO2a4, just started having the Access Violation today, and I've deleted and reinstalled msvcr120.dll repeatedly.

**Comment by GoslingMyles** [comment]
@DeadMor0z @xRedDragon I figured out my problem. I had .esp files in the Fallout 4/Data Directory. When I moved them to the proper folders in MO2a4, the access exception disappeared. The problem seems to be trying to get files from both the real and virtual directories.

**Comment by itunlimited** [comment]
Thank you @GoslingMyles for this tidbit.  It seems like the overwrite folder does not work properly.  It does not show that there are miscellaneous esp files in the Data folder.  I created a merge patch folder and added it as a mod in the MO mods folder and everything's gravy.

**Comment by scotty9090** [comment]
Same issue here just a few mins ago.  For me it seemed to be *any* file in the overwrite directory.  I modified an ESP in FO4Edit (keep backup was unchecked) and the file saved to the overwrite directory vs. the original mod's folder along with an (empty) FO4Edit Backups folder.  Moving the ESP to the original mod folder didn't solve the problem - I had to completely empty overwrite by removing the FO4Edit backup folder as well.

**Comment by blomstertj** [comment]
I'm having this problem too on Windows 10 64-bit. The game crashes before main menu when using Mod Organizer 2.0.6. Running the exact same mod list and exact same load order as I did previously. I had Fallout 4 and Mod Organizer on my non-Windows partition on a separate hard drive. It worked flawlessly. I uninstalled Fallout 4 and Mod Organizer and install them to C:\Games\Fallout 4 and C:\Games\Fallout 4 MO. I wanted faster load times with my SSD. The game does start up and doesn't crash when not using MO to launch. I tried running MO as admin but that did not help.

Here's another log but with log level set to Error only: https://drive.google.com/open?id=1wbZtWf64Kz36ZS8FdtwlHRhTT5SqyYBV9UzwKLZbpfw

The last line seems interesting to me. Any ideas?

**Comment by TanninOne** [comment]
please rerun with log level set to debug and send a new log.

**Comment by blomstertj** [comment]
Okay, TanninOne.  I reran it with the log level set to debug and here is the log.  https://drive.google.com/file/d/0B0Ctu5L4DOKwbl9PSmd6ZEtoQ0U/view?usp=sharing

**Comment by TanninOne** [comment]
Sorry, forgot to mention: you have to restart mo after changing the log level.

**Comment by blomstertj** [comment]
I ran it again after restarting MO and the log had the same content.

**Comment by GoslingMyles** [comment]
I had the issue with that .dll because my overwrite folder was not working at all. Having any loose .esps in the Fallout 4/Data directory caused the error, so moving all files not from Bethesda to mod folders in MO fixed it on my end and is your best bet.

**Comment by blomstertj** [comment]
The data folder is all Bethesda no custom esps are in there. My "over write" folder is empty in MO install directory. I copied the mods from the previous installation. Should they be completely reinstalled from scratch?

**Comment by GoslingMyles** [comment]
@blomstertj I'm going to level with you, I haven't played Fallout 4 in weeks. I had the problem and what  I did seemed to fix it. I left the /mods and /overwrite folders in their default location in /AppData/Local/Mod Organizer/Fallout 4 from the earlier alphas.

**Comment by blomstertj** [comment]
Mod Organizer is not located at that directory. I may try and reinstall all mods to fix it.

**Comment by blomstertj** [comment]
@TanninOne 
Okay so I completely uninstalled Mod Organizer and reinstalled it and re-downloaded my mods.  The issue persists.  After installing all my mods I hit run for Fallout4.exe and the log it gave me after crashing is here: https://drive.google.com/file/d/0B0Ctu5L4DOKwazlKTTJiSjRCdkE/view?usp=sharing
After restarting mod organizer and running the game it gave me this log: https://drive.google.com/file/d/0B0Ctu5L4DOKwbVFCZEUwMmowbGs/view?usp=sharing

**Comment by GoslingMyles** [comment]
@blomstertj Try reinstalling Visual Studio to the latest version, that is the file that is returning the error.

**Comment by blomstertj** [comment]
@GoslingMyles I have downloaded the installer and clicked repair and that did not help.

**Comment by dt78** [comment]
@blomstertj Uninstall, then reinstall. Don't use the repair option.

**Comment by blomstertj** [comment]
@dt78 Okay I will uninstall the C++ 2013 x64 and x86 and reinstall them.

**Comment by blomstertj** [comment]
@dt78 Uninstalling and reinstalling did not correct the issue.

**Comment by blomstertj** [comment]
@TanninOne Is there any residual data left behind in some weird folders like AppData after uninstallation?  I ask because when I reinstall it, it asks for game selection and it still lists my old game folder as D:\Games\Fallout 4 when that directory doesn't exist.  So is there some sort of config files it's leaving behind?

**Comment by blomstertj** [comment]
With the new release of MO it is fixed now.  I did uninstall Fo4 with Revo Uninstaller and after it was uninstalling it left a registry entry behind that said the installed path was D:\Games\Fallout 4.  Not sure if that was the problem or not.  I installed Fo4 to C:\Games and MO to C:\Games and all is working.  Unrelated, one of my mods crashes the game now where before it didn't.  It's not a big deal as it's just a dialogue interface mod.

@TanninOne thanks for your hard work.

**Comment by nickalex9** [comment]
My game completely broke down today and after much searching I came upon this thread. I have no experience with programming so everything in here is over my head. However I have been able to get FO4 working completely fine up until today with about 170 mods installed. I had latest Mo2, LOOT, FO4Edit all working fine. I tried to install F4SE to get the place everything mod. That seemed to go well. However I made the mistake of opening Steam and my game updated to 1.7.9. Then it became a poopshow. F4SE obviously no longer worked, and the game now crashes a few seconds into launch through MO but works fine outside of it. Loot also crashes in MO, works fine outside of it but does not detect plugins obviously. FO4Edit does not detect plugins, i also get the Access Violation error at the end of it. When trying to Sort through MO I get "loot failed. Exit code was 3221225477" I'm not sure if the new patch broke something or I did when installing F4SE. trying to figure out if there is anything I can do outside of a complete reinstall of everything.

**Comment by Jaarus** [comment]
I was having this problem repeatedly, and thought I got around it by restoring my ini files, but it was still occuring. I came across this thread while researching the issue with the MSVCR120.dll causing my crash. After reading through half the thread, I checked my Overwrite folder and it had my two looksmenu presets in there. I moved them to my main FO4 data directory so Overwrite is empty and now the game launches without the MSVCR120.dll error.

**Comment by VaporWatch** [comment]
Been trying to track down a fix for what I believe is the same issue without success.  MO seems to function  perfectly.....I can open x-edit no problem.....launching the game seems to be fine.....but when I try to open LOOT, it fails every time.

When I click LOOT in MO, the "MO is locked while the executable is running" pops up for a few moments. Another small window pops up which says "Mod Organizer" then "Preparing vfs".  The lock stays up for a few moments (maybe 2-3 seconds?) then both windows close and MO is back to normal.  

The oddest thing is there is no error reported.  When I attempt to open LOOT, the log at the bottom of the page doesn't report anything unusual. This is the log from my attempt to open LOOT:

12:30:22 [D] C:\Users\watch\AppData\Local\ModOrganizer\Fallout 4\profiles\Default\initweaks.ini saved
12:30:22 [D] C:\Users\watch\AppData\Local\ModOrganizer\Fallout 4\profiles\Default\lockedorder.txt saved
12:30:24 [D] C:\Users\watch\AppData\Local\ModOrganizer\Fallout 4\profiles\Default\lockedorder.txt saved

I have uninstalled LOOT and re-installed into the same directory, then a different directory.  I have checked the Overwrite folder and removed the "FO4Edit Backups" folder.  I have uninstalled the vcredistx_64.exe and vcredist_x86.exe and re-installed both starting with the x86 file.  I have uninstalled NMM completely as well.  

I can't find any other possible fixes so I'm open to suggestions.

I don't know if this will have any effect, but here's my usvfs log.  At least, I'm pretty sure it's from one of the times I tried to open LOOT.  
[usvfs-2016-09-24_16-28-31 -.txt](https://github.com/TanninOne/modorganizer/files/491230/usvfs-2016-09-24_16-28-31.-.txt)
and here's on which is, for some reason, WAY bigger
[usvfs-2016-09-24_15-57-20 -.txt](https://github.com/TanninOne/modorganizer/files/491232/usvfs-2016-09-24_15-57-20.-.txt)

I've resorted to sorting manually, so I'm gonna be here a while.  Any help is appreciated!

Watch

**Comment by RenegadeCoder** [comment]
I've been having these problems since the Vault DLC came out, and now I just came across [this gem](https://github.com/TanninOne/modorganizer/issues/567#issuecomment-202052431) from further up the page, and finally fixed everything by just deleting the couple of mods that I had downloaded from the in-game catalogue. Much thanks to @GoslingMyles!
