### ISSUE TITLE
MO 2.0.5 - LOOT failed. Exit code was: 1

### ISSUE THREAD

**Issue by JackLively** [TanninOne/modorganizer#734]
LOOT crashes every time I open it through Mod Organizer. I am using 2.0.5. I can open LOOT separately from it's own folder, however it does not seem to recognise my installed mods through Mod Organizer. I have tried redownloading and reinstalling both programs and even did a clean installation of both, yet the problem still persists. When I click 'Sort' in Mod Organizer, LOOT tries to start, only to give the error message: "loot failed. Exit code was: 1". When I try to start LOOT through Mod Organizer's menu, it gets to the stage where it is "parsing, merging and evaluating metadata", but an error message immediately appears; "LOOT.exe has stopped working", and it gives me no other option but "Close program". I have searched for a solution to this but I can't find anything online! If anyone could help I would be very thankful!

**Comment by pStyl3** [comment]
What is your operation system?
Is your OP up to date?
What happens, if you goto C:\%localappdata% and delete the LOOT folder there?
Is your plugins.txt in C:\%localappdata%\Fallout4\ set to be "read only"?

**Comment by JackLively** [comment]
My OS is Windows 10, if that's what you mean. I don't know what my OP is, but I assume you mean the Mod Organizer and LOOT, they are both up to date. I have already tried deleting the LOOT folder in Localappdata but it doesn't solve the issue. My plugins.txt is not set to read only. Sorry to be a nuisance.

**Comment by pantera160** [comment]
I am having the same issue. LOOT appears to start and then stops with the "loot failed. Exit code was: 1" message. It comes with the following error: "[loot] Error: invalid dll, variable loot_game_fo4 not found". MO is installed inside my game directory. This isn't on the "C" drive tho, no idea if this might be part of the issue.
OS: win10
Both LOOT and MO are up to date.

**Comment by MysticDaedra** [comment]
Having the same problem, same as above. Fresh install of MO2, meaning everything was deleted then reinstalled. I'm pretty sure this is a duplicate thread, there is already an Issue not too far below this one about this topic and this version of MO.

**Comment by JackLively** [comment]
I actually did a search of the forums for this issue, or keywords related
to it and it returned nothing, so I assumed it hadn't been filed yet. I
googled it, but the issue that Google returned was from this site, but had
nothing to do with my issue, so I posted it here.

**Comment by lumpyclumps** [comment]
@JackLively I fixed this error by doing the following:
1) Go to LOOT's github page.
2) Download Loot.API for the latest version
3) Extract the files to ModOrganizer's install directory, under the loot folder.  For me, this looked like C:\Program Files\ModOrganizer\loot.  It will replace the existing loot32.dll and will add a folder called "include".  I did not elect to keep the "docs" folder.

This fixed my issue next time I tried to run loot.

**Comment by ChristopherC71** [comment]
I have the same error and the above did not resolve my issue. Running Mod-O 2.0.5 with the latest Loot.

**Comment by JackLively** [comment]
I also tried that, it did not fix it. Sorry.

**Comment by IIIuminator** [comment]
@lumpyclumps your solution worked for me. The sort button is now working like it's supposed to.
@JackLively make sure you downloaded version 0.9.0 if you try sorting FO4 plugins. Any prior version does not support FO4.

**Comment by pStyl3** [comment]
@JackLively 
Sorry, I meant OS not OP, so I wanted to know if your operating system is up to date. Also, you aren't a nuisance, it was great from you to go out of your way to post a bug report. Problems can only be solved if they are reported. In any case, yes please try to update to LOOT v0.9.0 if you haven't already, and use the API "LOOT.API.0.9.0-0-g44a0d85.32.bit.7z" from GitHub, to update the loot32.dll MO is using.

@lumpyclumps 
You don't need to copy over the "include" folder that is contained within the API archive, just copying "loot32.dll" will do.

@lumpyclumps @ChristopherC71 
What operating system do you use? Windows 10?

**Comment by JackLively** [comment]
@pStyl3 Yes, my OS is up to date. I have already downloaded and installed the latest of all the things you mentioned above. :/

**Comment by xNine** [comment]
Again people, if worst comes to worst: download loot ([https://github.com/loot/loot/releases/tag/0.9.0](url)) and add the executable to mod organizer. Loading the actual loot application through mod organizer fulfills the same purpose as the built in loot button.

**Comment by MysticDaedra** [comment]
Unfortunately the latest standalone version of LOOT won't work for me, even though the built-in one does. I believe there is another issue already created that expounds on that problem.
